### ISSUE TITLE
Release a Homebrew package

### ISSUE THREAD

**Issue by kevinburke** [jorgebastida/awslogs#116]
It would be neat if you could run `brew install awslogs` and not need to worry about pip or Python or upgrading.

Here's a Formula for `httpie`, which I believe has a similar installation process: https://github.com/Homebrew/homebrew-core/blob/master/Formula/httpie.rb

**Comment by kevinburke** [comment]
I might just do this.

**Comment by kevinburke** [comment]
can you release a new version for 0.8.0?

**Comment by fiunchinho** [comment]
I'd love to have the latest version too! Thank you

**Comment by jorgebastida** [comment]
This is a great idea @kevinburke Just created the 0.8 tag so you can link to it

**Comment by jorgebastida** [comment]
I can see ``awslogs`` in hombrew! Thanks! closing
