### ISSUE TITLE
[Crash Report] UnicodeEncodeError

### ISSUE THREAD

**Issue by kakeim** [jorgebastida/awslogs#121]
Version: 0.8.0
Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]
boto3 version: 1.4.4
Platform: Windows-7-6.1.7601-SP1
Config: {'output_timestamp_enabled': False, 'output_group_enabled': True, 'end': '2/28/2017', 'log_group_name': 'Middleware', 'log_stream_name': 'ALL', 'aws_region': None, 'watch': False, 'aws_access_key_id': 'SENSITIVE', 'start': '2/1/2017', 'aws_profile': 'SENSITIVE', 'filter_pattern': None, 'aws_secret_access_key': 'SENSITIVE', 'output_ingestion_time_enabled': False, 'query': None, 'func': 'list_logs', 'aws_session_token': 'SENSITIVE', 'color_enabled': True, 'output_stream_enabled': True}
Args: ['C:\\Python27\\Scripts\\awslogs', 'get', 'Middleware', '--start=2/1/2017', '--end=2/28/2017']

Traceback (most recent call last):
  File "c:\python27\lib\site-packages\awslogs\bin.py", line 172, in main
    getattr(logs, options.func)()
  File "c:\python27\lib\site-packages\awslogs\core.py", line 187, in list_logs
    consumer()
  File "c:\python27\lib\site-packages\awslogs\core.py", line 184, in consumer
    print(' '.join(output))
  File "c:\python27\lib\codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
  File "c:\python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u200b' in position 131: character maps to <undefined>

**Comment by ligustah** [comment]
Ran into the same today, is there any workaround?
In my case it's complaining about this one: https://unicode-table.com/en/1F44D/

**Comment by ligustah** [comment]
Ok, I worked around it by modifying [a line in core.py](https://github.com/jorgebastida/awslogs/blob/c190641dee80f4955f4fc779af49efda5abfe52e/awslogs/core.py#L120) and basically hard-code a pattern to exclude that specific character:
```python
kwargs['filterPattern'] = "-👍"
```

**Comment by droberson8588** [comment]
I found a solution to this that works for all characters.

Within the windows console, enter "set PYTHONIOENCODING=utf-8" without quotes. You can then pipe to a file or application without encountering encoding errors. Note: This needs to be set for every instance of the command prompt that is opened. I have read that it is bad to set this permanently as it can cause other python tools to act up, so I would set it on a per application basis.

**Comment by mikeyjarvis19** [comment]
> I found a solution to this that works for all characters.
> 
> Within the windows console, enter "set PYTHONIOENCODING=utf-8" without quotes. You can then pipe to a file or application without encountering encoding errors. Note: This needs to be set for every instance of the command prompt that is opened. I have read that it is bad to set this permanently as it can cause other python tools to act up, so I would set it on a per application basis.

This worked, thank you!

**Comment by jorgebastida** [comment]
Fixed as part of https://github.com/jorgebastida/awslogs/pull/396
