### ISSUE TITLE
Stop printing full group / stream name?

### ISSUE THREAD

**Issue by jameswilsterman** [jorgebastida/awslogs#136]
Is it possible to filter out the group and stream name from every log statement? Mine are quite long and taking up lots of horizontal space in my terminal. Thanks.

**Comment by holgerreif** [comment]
Try built-in help
```
$ awslogs get -h 
<...>
  -G, --no-group        Do not display group name
  -S, --no-stream       Do not display stream name
```

**Comment by jameswilsterman** [comment]
thank you!
