### ISSUE TITLE
Use credentials profiles

### ISSUE THREAD

**Issue by alex88** [jorgebastida/awslogs#15]
It would be nice to use credential profiles as in aws cli:

```
aws s3 .. --profile company1
aws s3 .. --profile company2
```

it seems it's not actually possible

**Comment by johnhamelink** [comment]
+1 this would be great - you can currently get something similar by using `export AWS_PROFILE=profile_name`

**Comment by ejhayes** [comment]
You can also run `AWS_PROFILE=profile_name awslogs ...`

**Comment by jorgebastida** [comment]
Initially I was agains ``--profile`` but it looks like people are really used to this api because ``aws-cli``... so  ¯\_(ツ)_/¯ 

Could you please give a try to https://github.com/jorgebastida/awslogs/pull/29 before merging it into master?

**Comment by jorgebastida** [comment]
Merged
