### ISSUE TITLE
awslogs get crashes due to encoding error

### ISSUE THREAD

**Issue by edallnutt** [jorgebastida/awslogs#156]
Version: 0.10.0
Python: 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)]
boto3 version: 1.4.4
Platform: Windows-10-10.0.10586-SP0
Config: {'aws_access_key_id': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'aws_session_token': 'SENSITIVE', 'aws_profile': 'SENSITIVE', 'aws_region': None, 'log_group_name': '/aws/lambda/Search_Domain', 'log_stream_name': 'ALL', 'filter_pattern': None, 'watch': False, 'output_group_enabled': True, 'output_stream_enabled': True, 'output_timestamp_enabled': False, 'output_ingestion_time_enabled': False, 'start': "'2h'", 'end': None, 'color_enabled': True, 'query': None, 'func': 'list_logs'}
Args: ['C:\\Python36\\Scripts\\awslogs', 'get', '/aws/lambda/Search_Domain', "--start='2h'"]

Traceback (most recent call last):
  File "c:\python36\lib\site-packages\awslogs\bin.py", line 172, in main
    getattr(logs, options.func)()
  File "c:\python36\lib\site-packages\awslogs\core.py", line 196, in list_logs
    consumer()
  File "c:\python36\lib\site-packages\awslogs\core.py", line 185, in consumer
    print(' '.join(output))
  File "c:\python36\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 193-198: character maps to \<undefined\>

**Comment by jorgebastida** [comment]
Fixed as part of https://github.com/jorgebastida/awslogs/pull/396
