### ISSUE TITLE
codec can't encode character u'\ufffd' 

### ISSUE THREAD

**Issue by gjayanth715** [jorgebastida/awslogs#157]
Version: 0.10.0
Python: 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit
(Intel)]
boto3 version: 1.4.5
Platform: Windows-2008ServerR2-6.1.7601-SP1
Config: {'output_timestamp_enabled': False, 'output_group_enabled': False, 'end'
: None, 'log_group_name': '/aws/lambda/{Lambda-ID}', 'log_stream_name': 'ALL', 'aws_region': 'us-west-2', 'watch': False,
'aws_access_key_id': 'SENSITIVE', 'start': '1d', 'aws_profile': 'SENSITIVE', 'fi
lter_pattern': None, 'aws_secret_access_key': 'SENSITIVE', 'output_ingestion_tim
e_enabled': False, 'query': None, 'func': 'list_logs', 'aws_session_token': 'SEN
SITIVE', 'color_enabled': False, 'output_stream_enabled': False}
Args: ['C:\\Python27\\Scripts\\awslogs', 'get', '/aws/lambda/{Lambda-ID}', '--aws-region', 'us-west-2', '-s1d', '--no-colo
r', '--no-group', '--no-stream']

Traceback (most recent call last):
  File "c:\python27\lib\site-packages\awslogs\bin.py", line 172, in main
    getattr(logs, options.func)()
  File "c:\python27\lib\site-packages\awslogs\core.py", line 196, in list_logs
    consumer()
  File "c:\python27\lib\site-packages\awslogs\core.py", line 185, in consumer
    print(' '.join(output))
  File "c:\python27\lib\codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
  File "c:\python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\ufffd' in position
 1613: character maps to <undefined>

**Comment by chennareddy08** [comment]
I have also faced this issue
Testing started at 1:49 PM ...
C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pycharm\_jb_pytest_runner.py" --path D:/Automation/SP/tests/sm_sanity.py
Console output is saving to: D:\Automation
Launching pytest with arguments D:/Automation/SP/tests/sm_sanity.py in D:\Automation\SP\tests
============================= test session starts =============================
platform win32 -- Python 3.7.3, pytest-4.0.2, py-1.8.0, pluggy-0.8.0
rootdir: D:\Automation\SP\tests, inifile:
plugins: xdist-1.25.0, metadata-1.7.0, html-1.19.0, forked-0.2, bdd-3.1.1collected 1 item

sm_sanity.py F
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\_pytest\main.py", line 185, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\_pytest\main.py", line 225, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\hooks.py", line 284, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\_pytest\main.py", line 246, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\hooks.py", line 284, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\_pytest\runner.py", line 76, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\_pytest\runner.py", line 91, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\_pytest\runner.py", line 175, in call_and_report
INTERNALERROR>     hook.pytest_runtest_logreport(report=report)
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\hooks.py", line 284, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pycharm\teamcity\pytest_plugin.py", line 329, in pytest_runtest_logreport
INTERNALERROR>     self.report_test_failure(test_id, report)
INTERNALERROR>   File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pycharm\teamcity\pytest_plugin.py", line 255, in report_test_failure
INTERNALERROR>     self.report_test_output(report, test_id)
INTERNALERROR>   File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pycharm\teamcity\pytest_plugin.py", line 236, in report_test_output
INTERNALERROR>     dump_test_stdout(self.teamcity, test_id, test_id, data)
INTERNALERROR>   File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pycharm\teamcity\common.py", line 73, in dump_test_stdout
INTERNALERROR>     messages.testStdOut(test_id, chunk, flowId=flow_id)
INTERNALERROR>   File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pycharm\teamcity\messages.py", line 167, in testStdOut
INTERNALERROR>     self.message('testStdOut', name=testName, out=out, flowId=flowId)
INTERNALERROR>   File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pycharm\_jb_runner_tools.py", line 113, in message
INTERNALERROR>     _old_service_messages.message(self, messageName, **properties)
INTERNALERROR>   File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pycharm\teamcity\messages.py", line 81, in message
INTERNALERROR>     self.output.write(self.encode(message))
INTERNALERROR>   File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pycharm\teamcity\messages.py", line 48, in encode
INTERNALERROR>     value = value.encode(self.encoding)
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\encodings\cp1252.py", line 12, in encode
INTERNALERROR>     return codecs.charmap_encode(input,errors,encoding_table)
INTERNALERROR> UnicodeEncodeError: 'charmap' codec can't encode character '\ufffd' in position 4909: character maps to <undefined>

==================== 1 failed, 3 warnings in 22.36 seconds ====================

Process finished with exit code 0

**Comment by jorgebastida** [comment]
Fixed as part of https://github.com/jorgebastida/awslogs/pull/396
