### ISSUE TITLE
Loop forever bug

### ISSUE THREAD

**Issue by guba-cbaxley** [jorgebastida/awslogs#17]
[root@pl ~]# awslogs get /var/log/messages -s '2h'  --aws-region='us-east-1'
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/gevent/greenlet.py", line 519, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/awslogs/core.py", line 185, in _raw_events_queue_consumer
    timestamp, line = self.raw_events_queue.peek(timeout=1)
  File "/usr/lib64/python2.7/site-packages/gevent/queue.py", line 305, in peek
    self.getters.discard(waiter)
AttributeError: 'collections.deque' object has no attribute 'discard'
<Greenlet at 0x2c53730: <bound method AWSLogs._raw_events_queue_consumer of <awslogs.core.AWSLogs object at 0x2b93f10>>> failed with AttributeError

================================================================================
You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new
--------------------------------------------------------------------------------
Version: 0.0.2
Python: 2.7.3 (default, Aug  9 2012, 17:23:57) 
[GCC 4.7.1 20120720 (Red Hat 4.7.1-5)]
boto version: 2.38.0
Platform: Linux-3.11.10-100.fc18.x86_64-x86_64-with-fedora-18-Spherical_Cow
Config: {'output_group_enabled': True, 'end': None, 'aws_secret_access_key': 'SENSITIVE', 'log_stream_name': u'ALL', 'aws_region': u'us-east-1', 'watch': False, 'start': u'2h', 'log_group_name': u'/var/log/messages', 'func': 'list_logs', 'aws_access_key_id': 'SENSITIVE', 'color_enabled': True, 'output_stream_enabled': True}
Args: ['/bin/awslogs', 'get', '/var/log/messages', '-s', '2h', '--aws-region=us-east-1']

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/awslogs/bin.py", line 121, in main
    getattr(logs, options.func)()
  File "/usr/lib/python2.7/site-packages/awslogs/core.py", line 236, in list_logs
    pool.join()
  File "/usr/lib64/python2.7/site-packages/gevent/pool.py", line 461, in join
    self._empty_event.wait(timeout=timeout)
  File "/usr/lib64/python2.7/site-packages/gevent/event.py", line 86, in wait
    result = self.hub.switch()
  File "/usr/lib64/python2.7/site-packages/gevent/hub.py", line 510, in switch
    return greenlet.switch(self)
LoopExit: ('This operation would block forever', <Hub at 0x2b17730 epoll default pending=0 ref=0 fileno=3 resolver=<gevent.resolver_thread.Resolver at 0x2c76e10 pool=<ThreadPool at 0x2cce710 0/8/10>> threadpool=<ThreadPool at 0x2cce710 0/8/10>>)
================================================================================

**Comment by jorgebastida** [comment]
I've just pushed a new version (0.1.0) to pypi which should fix this issue.
https://pypi.python.org/pypi/awslogs/0.1.0

**Comment by guba-cbaxley** [comment]
Thanks
