### ISSUE TITLE
pick up new streams as they are added

### ISSUE THREAD

**Issue by mmerickel** [jorgebastida/awslogs#170]
I'm using `awslogs` to watch logs piped from heroku and a new stream is created for each dyno. Heroku automatically creates new dynos each day, causing new streams to be created in cloudwatch. Currently when the new streams are created I need to restart `awslogs`. I was expecting `awslogs` to poll for new streams periodically so that the new log data would appear without requiring a restart.

**Comment by blueyed** [comment]
You are using `-w` then, right?
What is your invocation exactly?

Currently streams are being filtered/received in the beginning only (via `_get_streams_from_pattern`), but only if not specified (or `ALL` is used).

Are you mixing streams and log groups maybe?

**Comment by mmerickel** [comment]
My invocation is `awslogs get my-log-group ALL -SG --timestamp -w`. The situation where streams are only filtered/received in the beginning is the exact thing I'm complaining about I think so ift here's a way around it then I don't see it right now.

**Comment by jorgebastida** [comment]
Going to follow up here https://github.com/jorgebastida/awslogs/issues/214
