### ISSUE TITLE
Document STREAM_EXPRESSION Syntax

### ISSUE THREAD

**Issue by Miserlou** [jorgebastida/awslogs#180]
How do I use `STREAM_EXPRESSION` if I have multiple streams? I see that it exists, but I have no idea what format this expression is supposed to be. Can you show an example fetching multiple named streams in the README, or include a link to a place where this term is described?

**Comment by xueshanf** [comment]
I am using containerized version, but  it should be similar with awslogs command:

```console
$ docker run --rm -it -v $HOME/.aws:/root/.aws xueshanf/awslogs streams <log group name>  --profile=<aws profile>
ip-10-10-1-12.us-west-2.compute.internal
ip-10-10-1-30.us-west-2.compute.internal
ip-10-10-1-36.us-west-2.compute.internal
ip-10-10-2-43.us-west-2.compute.internal
```

Then I can do:
```console
$ docker run --rm -it -v $HOME/.aws:/root/.aws xueshanf/awslogs get <log group name> ip-10-10-2-43.us-west-2.compute.internal  --profile=<aws profile>
```
Or with reg expression:

```console
$ docker run --rm -it -v $HOME/.aws:/root/.aws xueshanf/awslogs get <log group name> ip-10-10-2-*  --profile=<aws profile>
```
Hope this helps.

**Comment by jorgebastida** [comment]
https://github.com/jorgebastida/awslogs/issues/217 should fix this documentation issue
