### ISSUE TITLE
assume role

### ISSUE THREAD

**Issue by if414013** [jorgebastida/awslogs#186]
Hi ...
is it possible to set up aws log to read flog stream from another aws account with assume role?

**Comment by bgiaccio** [comment]
awslogs simply uses the profile configured in your AWS config files, so the following will work provided the role you are assuming allows you access to CloudWatch.
 
Step 1: Assume you have a profile configured named **default** in your $HOME/.aws/credentials
Step 2: Add the role you are assuming to your $HOME/.aws/config, like this replacing 123456789012 with a valid accountId and ROLE_NAME with the role you are assuming
```shell
[profile someName]
role_arn = arn:aws:iam::123456789012:role/ROLE_NAME
source_profile = default
region = us-east-1
```
Step 3: `awslogs groups --profile someName`

**Comment by jorgebastida** [comment]
Thank you very much @bgiaccio for the detailed response!
