### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by guyisra** [jorgebastida/awslogs#191]
This is super popular and useful, but almost a year of not maintenance with 5 PR ..

Is this still maintained or maybe maintainers should be added to the repo? @jorgebastida

**Comment by jorgebastida** [comment]
I'm afraid the quick answer is no. That being said... I am open to getting some help and incorporate some maintainers.

**Comment by blueyed** [comment]
@jorgebastida 
I'd be happy to help, and likely others as well.

See my latest PRs, which I'd like to get feedback on also.

**Comment by guyisra** [comment]
\o/
horray

**Comment by jorgebastida** [comment]
I am going to bite the bullet and try to do a mayor release fixing most of the common errors now that I have more spare time.
