### ISSUE TITLE
Watch does not work reliably

### ISSUE THREAD

**Issue by blueyed** [jorgebastida/awslogs#195]
`awslogs get -w --timestamp project-workers-test` shows messages from `celery-worker-project.container`, but does not emit/show (any?) new log entries - at least not for the `celery-worker-project.container` stream.

`awslogs get -w --timestamp project-workers-test celery-worker-project.container` aborts with `No streams match your pattern 'celery-worker-project.container'.` (fixed by https://github.com/jorgebastida/awslogs/pull/185).

Adding `-s 1h` then shows log entries, and also updates for new entries.
This looks like the `-s` (since) is also used when querying all stream names, which shouldn't be done.

The main issue here appears to be that there is a `nextToken` in the response when not specifying a stream name, which then does not get deleted.

Additional info:
awslogs 0.10.0

```
% awslogs streams project-workers-test
CRON                                                             
apport.service
celery-worker-project.container
collectd.service
cron.service
kernel
landscape-client.service
salt-minion.service
session-8270.scope
ssh.service
sshd
systemd
systemd-logind.service
```

**Comment by tekumara** [comment]
When running `awslogs get [log_group_name] [log_stream_name] --watch --timestamp -G -S -s'1m ago'` I've noticed it hasn't always fetching the latest log lines in real-time.

If I restart awslogs I see the newer log lines.

**Comment by jorgebastida** [comment]
Trying to cleanup issues atm. Will follow up here https://github.com/jorgebastida/awslogs/issues/235
