### ISSUE TITLE
Credentials Fail : NoAuthHandlerFound: No handler was ready to authenticate.

### ISSUE THREAD

**Issue by labithiotis** [jorgebastida/awslogs#2]
Trying to use awslogs for the first time, already had aws-cli setup with credentials but get this error:

Version: 0.0.1
Python: 2.7.8 (default, Sep 26 2014, 11:28:16)
[GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)]
boto version: 2.38.0
Platform: Darwin-14.3.0-x86_64-i386-64bit
Config: {'color_enabled': True, 'aws_region': u'eu-west-1', 'aws_access_key_id': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'func': 'list_groups'}
Args: ['/usr/local/bin/awslogs', 'groups']

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/awslogs/bin.py", line 115, in main
    logs = AWSLogs(**vars(options))
  File "/usr/local/lib/python2.7/site-packages/awslogs/core.py", line 83, in __init__
    aws_secret_access_key=self.aws_secret_access_key
  File "/usr/local/lib/python2.7/site-packages/awslogs/core.py", line 27, in __init__
    self.connection = botologs.connect_to_region(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/boto/logs/__init__.py", line 40, in connect_to_region
    return region.connect(**kw_params)
  File "/usr/local/lib/python2.7/site-packages/boto/regioninfo.py", line 187, in connect
    return self.connection_cls(region=self, **kw_params)
  File "/usr/local/lib/python2.7/site-packages/boto/logs/layer1.py", line 107, in __init__
    super(CloudWatchLogsConnection, self).__init__(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1100, in __init__
    provider=provider)
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 569, in __init__
    host, config, self.provider, self._required_auth_capability())
  File "/usr/local/lib/python2.7/site-packages/boto/auth.py", line 987, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))
NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials

**Comment by jorgebastida** [comment]
Looks related to this https://github.com/boto/boto/issues/2383 - Could you please try to a different version  of boto (``2.32.0``) as mentioned in that issue?

**Comment by labithiotis** [comment]
When I install version 2.32.0 I get `awslogs can't connecto to AWS.` (pip install -I boto=2.32.0)

If I then uninstall and reinstall awslogs I get same issue as before, and doing the above again the result is the same.

**Comment by jorgebastida** [comment]
Ok, I think I've found the problem. I am right thinking your credentials are located in ``~/.aws/config`` instead of ``~/.aws/credentials``? if that it the case, ``aws-cli`` will work, but because that file is suppose to not contain sensitive options, boto will not use them http://boto.readthedocs.org/en/latest/boto_config_tut.html#details

This is the comment I'm referring to:
```
The AWS CLI will also read credentials from the config file. If you want to keep all of 
your profile settings in a single file, you can. If there are ever credentials in both 
locations  for a profile (say you used aws configure to update the profile's keys), 
the keys in the  credentials file will take precendence.

If you use one of the SDKs in addition to the AWS CLI, you may notice additional 
warnings if credentials are not stored in their own file.
```

I've put my credentials as part of ``~/.aws/config`` and remove my  ``~/.aws/credentials`` and I've reproduce the same error you got.

If you confirm this is the case for you, I'll try to catch this error and return some helpful error message.

**Comment by labithiotis** [comment]
I renamed the config to credentials which worked. 

Getting another issue (which may be related) running $`awslogs groups` and $`awslogs get JAVA Production -s1d` gives no results but with `aws logs get-log-events --region us-east-1 --log-group-name Java --log-stream-name Production` I get the logs.

**Comment by jorgebastida** [comment]
I think it is related to this https://github.com/jorgebastida/awslogs/blob/master/awslogs/bin.py#L44-L48 For some reason in the past... I made ``eu-west-1`` the default region... which is probably not a good idea. Will investigate if making it None makes ``boto`` use whatever you have configured in your ``~/.aws/config`` and make it None if so.

**Comment by jorgebastida** [comment]
Well, sorry as a workaround you can run... ``$ awslogs --aws-region=us-east-1 groups`` and it should work :)

**Comment by jorgebastida** [comment]
As part of this fix I've make a requirement to provide a valid aws-region using ``--aws-region`` or ``AWS_REGION`` env variable. I think that should be enough in order to make this not happen again.

**Comment by kiranpy** [comment]
after creating a dir ~/.aws/credentials the problem is solved.

**Comment by fernandomariano** [comment]
I solved this issue running aws configure
