### ISSUE TITLE
Issues with get from cloudwatch syslog entries

### ISSUE THREAD

**Issue by macktab** [jorgebastida/awslogs#208]
`Version: 0.10.0
Python: 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609]
boto3 version: 1.7.59
Platform: Linux-4.4.0-1052-aws-x86_64-with-Ubuntu-16.04-xenial
Config: {'output_timestamp_enabled': False, 'output_group_enabled': True, 'end': None, 'log_group_name': 'Production-56-App-Syslog', 'log_stream_name': 'ALL', 'aws_region': None, 'watch': False, 'aws_access_key_id': 'SENSITIVE', 'start': '5m', 'aws_profile': 'SENSITIVE', 'filter_pattern': None, 'aws_secret_access_key': 'SENSITIVE', 'output_ingestion_time_enabled': False, 'query': None, 'func': 'list_logs', 'aws_session_token': 'SENSITIVE', 'color_enabled': True, 'output_stream_enabled': True}
Args: ['/usr/local/bin/awslogs', 'get', 'Production-56-App-Syslog', 'ALL', '-s5m', '--region', 'us-east-1']

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/awslogs/bin.py", line 172, in main
    getattr(logs, options.func)()
  File "/usr/local/lib/python2.7/dist-packages/awslogs/core.py", line 196, in list_logs
    consumer()
  File "/usr/local/lib/python2.7/dist-packages/awslogs/core.py", line 185, in consumer
    print(' '.join(output))
  File "/usr/lib/python2.7/codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 171: ordinal not in range(128)`

**Comment by jorgebastida** [comment]
Will followup on this issue as part of https://github.com/jorgebastida/awslogs/issues/215
