### ISSUE TITLE
Problems to stop the command

### ISSUE THREAD

**Issue by vlcinsky** [jorgebastida/awslogs#21]
Debian Jessie 64 bit, Python 2.7.9

Using awslogs==0.1.1:

    $ pip freeze                                                                                                                                                          
    argparse==1.2.1
    awslogs==0.1.1
    boto3==1.2.1
    botocore==1.3.1
    docutils==0.12
    futures==2.2.0
    jmespath==0.9.0
    python-dateutil==2.4.2
    six==1.10.0
    termcolor==1.1.0
    wsgiref==0.1.2

Calling `get` without any argumen (what is an error):

    $ awslogs get                                                                                                                                                                                     (env: awslogs)
    Exception in thread Thread-1:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
        self.run()
      File "/usr/lib/python2.7/threading.py", line 763, in run
        self.__target(*self.__args, **self.__kwargs)
      File "/home/javl/.virtualenvs/awslogs/local/lib/python2.7/site-packages/awslogs/core.py", line 139, in generator
        response = self.client.filter_log_events(**kwargs)
      File "/home/javl/.virtualenvs/awslogs/local/lib/python2.7/site-packages/botocore/client.py", line 310, in _api_call
        return self._make_api_call(operation_name, kwargs)
      File "/home/javl/.virtualenvs/awslogs/local/lib/python2.7/site-packages/botocore/client.py", line 395, in _make_api_call
        raise ClientError(parsed_response, operation_name)
    ClientError: An error occurred (ResourceNotFoundException) when calling the FilterLogEvents operation: The specified log group does not exist.

and one cannot stop the program by Ctrl-C. I had to use `killall awslogs`

Similarly it behaves, when I use wrong group name.

Using proper group name and `--watch` option works, but there is also no
"clean" way to stop it by Ctrl-C.

It only reacts by:

    ^CYou pressed Ctrl+C!

but hangs untill I kill it.

**Comment by ejhayes** [comment]
@vlcinsky I have added a PR for this.

**Comment by vlcinsky** [comment]
Thanks @ejhayes .
I confirm it works well.
Tested by installing awslogs==0.1.2
