### ISSUE TITLE
Error when using && in filter-pattern

### ISSUE THREAD

**Issue by phuongnt287** [jorgebastida/awslogs#210]
I can use pattern like this to filter log on CloudWatch log group
{$.kubernetes.namespace_name="abc" && $.kubernetes.container_name="def"}
But it will be throw an InvalidParameterException "If a filter pattern starts with '{' it must end with '}'" when i use this pattern in awslogs command: 
awslogs get GROUP --filter-pattern={$.kubernetes.namespace_name="abc" && $.kubernetes.container_name="def"} --start='10 minute'

Don't it support the filter pattern?

**Comment by cykl** [comment]
Did you properly quote filter-pattern value?

```
awslogs get GROUP --filter-pattern='{$.kubernetes.namespace_name="abc" && $.kubernetes.container_name="def"}' --start='10 minute'
```

**Comment by phuongnt287** [comment]
No, I missed quote filter-pattern value, I have tried again with quote and it get logs seem OK. Thank you for your support.
