### ISSUE TITLE
Removing ANSI escape sequence from output

### ISSUE THREAD

**Issue by mattehicks** [jorgebastida/awslogs#211]
Is there any way to print the output without the ANSI codes?
ie: 

[32m log-name [0m [36m /log-group

log-name  /log-group

**Comment by apinkney97** [comment]
I feel like the default coloration should depend on the result of `sys.stdout.isatty()`.

I'm happy to submit a PR to this effect.

Maybe we should do the same thing `grep` does, and have `--color={never|auto|always}`, where `auto` means only if `sys.stdout.isatty()` is `True`.

**Comment by jorgebastida** [comment]
Fixed as part of ``0.11.0`` Thanks!
