### ISSUE TITLE
Write tests for unicode messages in python 2.7 (UnicodeEncodeError)

### ISSUE THREAD

**Issue by jmilesb** [jorgebastida/awslogs#215]
================================================================================
You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new
--------------------------------------------------------------------------------
Version: 0.10.0
Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609]
boto3 version: 1.9.9
Platform: Linux-4.4.0-17134-Microsoft-x86_64-with-Ubuntu-16.04-xenial
Config: {'output_timestamp_enabled': False, 'output_group_enabled': True, 'end': None, 'log_group_name': '/aws/lambda/markdownToHTMLwithSpeech', 'log_stream_name': 'ALL', 'aws_region': None, 'watch': False, 'aws_access_key_id': 'SENSITIVE', 'start': '2h', 'aws_profile': 'SENSITIVE', 'filter_pattern': None, 'aws_secret_access_key': 'SENSITIVE', 'output_ingestion_time_enabled': False, 'query': None, 'func': 'list_logs', 'aws_session_token': 'SENSITIVE', 'color_enabled': True, 'output_stream_enabled': True}
Args: ['/usr/local/bin/awslogs', 'get', '/aws/lambda/markdownToHTMLwithSpeech', '--profile', 'me', '--start=2h']

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/awslogs/bin.py", line 172, in main
    getattr(logs, options.func)()
  File "/usr/local/lib/python2.7/dist-packages/awslogs/core.py", line 196, in list_logs
    consumer()
  File "/usr/local/lib/python2.7/dist-packages/awslogs/core.py", line 185, in consumer
    print(' '.join(output))
  File "/usr/lib/python2.7/codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 197: ordinal not in range(128)

**Comment by jorgebastida** [comment]
Fixed as part of https://github.com/jorgebastida/awslogs/pull/396
