### ISSUE TITLE
Option to disable group name & stream name labels

### ISSUE THREAD

**Issue by nabilfreeman** [jorgebastida/awslogs#216]
Hey there, first off I love this tool!

There is just one problem... when "watching" logs live, the log group and stream takes up like 100 characters on my screen and there's no way to disable it.

<img width="747" alt="screen shot 2018-09-24 at 14 21 45" src="https://user-images.githubusercontent.com/2470659/45954619-69f78a00-c005-11e8-8c04-00b7ab6ba5fb.png">

*🔼I want to hide the green and blue text above 🔼*

When downloading the logs to file, I figured out a bash regex that gets rid of them but it would be great to have a proper config option in awslogs for live streaming.

```
# remove everything up to the second space
sed -i -e "s/^[^[:space:]]*[[:space:]][^[:space:]]*[[:space:]]//g" $FINAL_LOG
```

Thanks!

p.s. Renaming the log groups to something shorter is really hard in Elastic Beanstalk, because every time you rebuild the environment it forgets the name change.

**Comment by nabilfreeman** [comment]
I found a good solution. You can pipe the stream output through sed in the same way as the file!

This regex is cross-platform (Linux & MacOS): `s/^[^[:space:]]*[[:space:]][^[:space:]]*[[:space:]]//g`

```
REGION="eu-west-1"

# awslogs prefixes every line with the log group and stream. let's remove this info
# e.g. /aws/elasticbeanstalk/environment i-streamname12343 +++MY ACTUAL LOGS HERE+++
# remove everything up to the second space
REGEX="s/^[^[:space:]]*[[:space:]][^[:space:]]*[[:space:]]//g"

# run the command to stream logs, and pipe it through sed so we can filter out log group and stream name labels
awslogs get $LOG_GROUP ALL --watch --aws-region=$REGION | sed $REGEX
```

**Comment by cykl** [comment]
Have you tried `--no-group --no-stream`?

**Comment by jorgebastida** [comment]
@cykl is right - that is the expected way to remove both the group and stream name form the output. Thanks!

**Comment by nabilfreeman** [comment]
Oh right! Pretty funny that there was a built-in option.

I couldn't find it anywhere in the README or docs.

Btw, I learnt a lot about bash through that exercise 😜

**Comment by BinaryShrub** [comment]
I had a hard time with this too. It'd be great to see this in the README!
