### ISSUE TITLE
Support to run awslogs behind HTTP proxy

### ISSUE THREAD

**Issue by perma** [jorgebastida/awslogs#218]
Hi, thanks for an awesome tool!

It would be great if you could add support to run this tool when behind a HTTP proxy so it is possible to use the tool at work as well.

I found some examples on how to configure proxy in boto3:
https://stackoverflow.com/questions/33480108/how-do-you-use-an-http-https-proxy-with-boto3

A solution could be to add the proxy configuration based on if the OS environment variables "HTTP_PROXY/http_proxy" and/or "HTTPS_PROXY/https_proxy" is set.

**Comment by kiesel** [comment]
Actually, I use it behind a proxy and it works just fine. I've just set the `http_proxy|HTTP_PROXY|https_proxy|HTTPS_PROXY` environment variables to point to my proxy...

**Comment by jorgebastida** [comment]
Yes, setting the default enviromental variables for the proxy should do the trick
