### ISSUE TITLE
Exception when using the --profile option

### ISSUE THREAD

**Issue by moormaan** [jorgebastida/awslogs#219]
First of all, thanks for `awslogs`! It truly is made for humans.

This bug started appearing when I tried using the `--profile` option for the first time. Even though there seems to be mention of not specifying the region in the stack trace, the same thing happens irrespective of whether I use the `--region` option or no.

I tried upgrading the `awslogs` package through pip, but it seems to be at the latest version.

```
================================================================================
You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new
--------------------------------------------------------------------------------
Version: 0.10.0
Python: 2.7.15 (default, May 18 2018, 13:51:20)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
boto3 version: 1.7.19
Platform: Darwin-18.0.0-x86_64-i386-64bit
Config: {'output_timestamp_enabled': False, 'output_group_enabled': True, 'end': None, 'log_group_name': 'tstat-fw-waf-prod', 'log_stream_name': 'ALL', 'aws_region': None, 'watch': False, 'aws_access_key_id': 'SENSITIVE', 'start': '1m', 'aws_profile': 'SENSITIVE', 'filter_pattern': None, 'aws_secret_access_key': 'SENSITIVE', 'output_ingestion_time_enabled': False, 'query': None, 'func': 'list_logs', 'aws_session_token': 'SENSITIVE', 'color_enabled': True, 'output_stream_enabled': True}
Args: ['/usr/local/bin/awslogs', 'get', 'tstat-fw-waf-prod', '--start=1m', '--profile', 'ap2-prod', '--region', 'us-east-1']

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/awslogs/bin.py", line 168, in main
    logs = AWSLogs(**vars(options))
  File "/usr/local/lib/python2.7/site-packages/awslogs/core.py", line 62, in __init__
    region_name=self.aws_region
  File "/usr/local/lib/python2.7/site-packages/boto3/__init__.py", line 83, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python2.7/site-packages/botocore/session.py", line 861, in create_client
    client_config=config, api_version=api_version)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 76, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 285, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python2.7/site-packages/botocore/args.py", line 45, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/usr/local/lib/python2.7/site-packages/botocore/args.py", line 111, in compute_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 358, in resolve
    service_name, region_name)
  File "/usr/local/lib/python2.7/site-packages/botocore/regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "/usr/local/lib/python2.7/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
NoRegionError: You must specify a region.
================================================================================
```

**Comment by mbildner** [comment]
@moormaan as a temporary workaround you can add a `region` entry to the profile you're using.

I'm having the same problem using the cli btw

**Comment by jmromer** [comment]
> @moormaan as a temporary workaround you can add a region entry to the profile you're using.

@mbildner Is that confirmed to work?  I have `region` set in the profile, but it has no effect:

```
# ~/.aws/config
[myprofile]
output = json
region = us-east-1
```

```
% awslogs get /aws/lambda/webapp-dev  --profile=myprofile

================================================================================
You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new
--------------------------------------------------------------------------------
Version: 0.10.0
Python: 3.7.0 (default, Jun 29 2018, 20:13:13)
[Clang 9.1.0 (clang-902.0.39.2)]
boto3 version: 1.4.4
Platform: Darwin-18.0.0-x86_64-i386-64bit
Config: {'aws_access_key_id': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'aws_session_token': 'SENSITIVE', 'aws_profile': 'SENSITIVE', 'aws_region': None, 'log_group_name': '/aws/lambda/webapp-dev', 'log_stream_name': 'ALL', 'filter_pattern': None, 'watch': False, 'output_group_enabled': True, 'output_stream_enabled': True, 'output_timestamp_enabled': False, 'output_ingestion_time_enabled': False, 'start': '5m', 'end': None, 'color_enabled': True, 'query': None, 'func': 'list_logs'}
Args: ['/usr/local/bin/awslogs', 'get', '/aws/lambda/webapp-dev', '--profile=myprofile']

Traceback (most recent call last):
  File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/awslogs/bin.py", line 168, in main
    logs = AWSLogs(**vars(options))
  File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/awslogs/core.py", line 62, in __init__
    region_name=self.aws_region
  File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/boto3/__init__.py", line 83, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/botocore/session.py", line 836, in create_client
    client_config=config, api_version=api_version)
  File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/botocore/client.py", line 70, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/botocore/client.py", line 224, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/botocore/args.py", line 45, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/botocore/args.py", line 103, in compute_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/botocore/client.py", line 297, in resolve
    service_name, region_name)
  File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/botocore/regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
================================================================================
```

**Comment by sarbajitdutta** [comment]
> > @moormaan as a temporary workaround you can add a region entry to the profile you're using.
> 
> @mbildner Is that confirmed to work? I have `region` set in the profile, but it has no effect:
> 
> ```
> # ~/.aws/config
> [myprofile]
> output = json
> region = us-east-1
> ```
> ```
> % awslogs get /aws/lambda/webapp-dev  --profile=myprofile
> 
> ================================================================================
> You've found a bug! Please, raise an issue attaching the following traceback
> https://github.com/jorgebastida/awslogs/issues/new
> --------------------------------------------------------------------------------
> Version: 0.10.0
> Python: 3.7.0 (default, Jun 29 2018, 20:13:13)
> [Clang 9.1.0 (clang-902.0.39.2)]
> boto3 version: 1.4.4
> Platform: Darwin-18.0.0-x86_64-i386-64bit
> Config: {'aws_access_key_id': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'aws_session_token': 'SENSITIVE', 'aws_profile': 'SENSITIVE', 'aws_region': None, 'log_group_name': '/aws/lambda/webapp-dev', 'log_stream_name': 'ALL', 'filter_pattern': None, 'watch': False, 'output_group_enabled': True, 'output_stream_enabled': True, 'output_timestamp_enabled': False, 'output_ingestion_time_enabled': False, 'start': '5m', 'end': None, 'color_enabled': True, 'query': None, 'func': 'list_logs'}
> Args: ['/usr/local/bin/awslogs', 'get', '/aws/lambda/webapp-dev', '--profile=myprofile']
> 
> Traceback (most recent call last):
>   File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/awslogs/bin.py", line 168, in main
>     logs = AWSLogs(**vars(options))
>   File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/awslogs/core.py", line 62, in __init__
>     region_name=self.aws_region
>   File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/boto3/__init__.py", line 83, in client
>     return _get_default_session().client(*args, **kwargs)
>   File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/boto3/session.py", line 263, in client
>     aws_session_token=aws_session_token, config=config)
>   File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/botocore/session.py", line 836, in create_client
>     client_config=config, api_version=api_version)
>   File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/botocore/client.py", line 70, in create_client
>     verify, credentials, scoped_config, client_config, endpoint_bridge)
>   File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/botocore/client.py", line 224, in _get_client_args
>     verify, credentials, scoped_config, client_config, endpoint_bridge)
>   File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/botocore/args.py", line 45, in get_client_args
>     endpoint_url, is_secure, scoped_config)
>   File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/botocore/args.py", line 103, in compute_client_args
>     service_name, region_name, endpoint_url, is_secure)
>   File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/botocore/client.py", line 297, in resolve
>     service_name, region_name)
>   File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/botocore/regions.py", line 122, in construct_endpoint
>     partition, service_name, region_name)
>   File "/usr/local/Cellar/awslogs/0.10_1/libexec/lib/python3.7/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
>     raise NoRegionError()
> botocore.exceptions.NoRegionError: You must specify a region.
> ================================================================================
> ```
> **Update**: Adding the `region` entry to `~/.aws/credentials` instead of `~/.aws/config` seems to resolve this.

Agreed this solve my issue as well adding `region` to `credentials`. Whats the way to specify region using `awslogs`?
