### ISSUE TITLE
Hotkey shortcut to clear screen when on --watch

### ISSUE THREAD

**Issue by binaryPUNCH** [jorgebastida/awslogs#243]
Should be a simple implementation, I assume. But wouldn't it be nice if we could clear the screen when using `--watch`? I suggest pressing c clears the screen.

**Comment by bgiaccio** [comment]
Should be a key binding in your terminal. Mac terminal and iterm are command-k
Gnome terminal isn't bound but can be. 
Xterm is ctrl-a but you can rebind it

**Comment by jorgebastida** [comment]
@bgiaccio  is correct. This should be handled by your terminal. I do user iTerm2 and ``⌘R`` does the trick.

**Comment by jorgebastida** [comment]
Closing as this is not an awslogs bug
