### ISSUE TITLE
Grab VPC Flow logs for a specific ENI

### ISSUE THREAD

**Issue by fitchtravis** [jorgebastida/awslogs#244]
Hi.

Firstly, awesome tool!!! Secondly is it possible to get the logs for a specific ENI without having to use grep/awk/sed?

Thanks

**Comment by jorgebastida** [comment]
I don't know what those log lines look like... but give it a look to the "Filter option" section in the readme (https://github.com/jorgebastida/awslogs#filter-options), that might help you.

**Comment by jorgebastida** [comment]
Closing as this is not an awslogs bug.
