### ISSUE TITLE
Support `--filter-pattern` option

### ISSUE THREAD

**Issue by vlcinsky** [jorgebastida/awslogs#25]
Writing about AWS Logs CLI tools http://stackoverflow.com/a/33636237/346478 I have realized, that `awslogs` does not support `filter patterns`.

Adding filter patterns in the way `AWSCLI` option `--filter-pattern` is doing would be handy.

The method
[CloudWatchLogs.Client.filter_log_events](http://boto3.readthedocs.org/en/latest/reference/services/logs.html#CloudWatchLogs.Client.filter_log_events)
offers the `filterPattern` parameter for that.

**Comment by jorgebastida** [comment]
Will give it a try over the weekend, thanks!

**Comment by adamchainz** [comment]
+1 :smile:

**Comment by johnhamelink** [comment]
+1 - I'd also like to see ignore patterns too if possible!

I use cloudwatch logs for log storage and our web server's logs are full of pings from ELB to our app - being able to filter them out of cloudwatch would make reading the logs much easier :eyeglasses:

**Comment by adamchainz** [comment]
@johnhamelink The `FilterLogEvents` [API endpoint](http://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_FilterLogEvents.html) only allows filtering, not ignoring; however you can write negative patterns (`x != y` etc.) - see the [search syntax](http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/FilterAndPatternSyntax.html).

**Comment by jorgebastida** [comment]
Hello! I have a working version here https://github.com/jorgebastida/awslogs/pull/28 If you could give it a try before merging it into master... it would be nice!

Thanks

**Comment by jorgebastida** [comment]
This is now merged into master

**Comment by vlcinsky** [comment]
Nice. Tested with space delimited log records, it works for me, some errors are printed for invalid patterns, but this shall be resolved by learning the patterns.
Did not test for JSON yet.
