### ISSUE TITLE
Feature Request: Hide log group and stream

### ISSUE THREAD

**Issue by furstenheim** [jorgebastida/awslogs#304]
Hi,
Great tool. Is there a way to avoid showing the log group and stream on each line? It makes it hard to read. Also it is slightly redundant, since I already know what log group I'm requesting.

I could help with the implementation.

Thanks

**Comment by gene1wood** [comment]
Ya, these options are already present, just use the command line arguments `--no-group --no-stream`

**Comment by furstenheim** [comment]
Great thanks
