### ISSUE TITLE
Get all / multiple groups

### ISSUE THREAD

**Issue by blueyed** [jorgebastida/awslogs#34]
The synopsis for `awslog get` says:

> awslogs get [GROUP [STREAM_EXPRESSION]]

But `GROUP` is not optional.

It would be nice, if `awslogs get` would retrieve all streams in all groups - allowing for `awslogs get --watch` to watch everything.

Additionally `GROUP` could also allow for (regular) expressions to specify multiple, but not all of them.

**Comment by jorgebastida** [comment]
Thank you very much for the suggestion @blueyed but unfortunately there is no way to retrieve logs from several groups at the same time (http://boto3.readthedocs.org/en/latest/reference/services/logs.html#CloudWatchLogs.Client.get_log_events).

We could (as we did in 0.1) retrieve logs manually from several streams, and merge them on the fly doing some witchcraft... but the result wasn't very stable, nor maintainable.

Will come back to this as soon as AWS provides some api for doing this in boto3.

Thanks!

**Comment by jorgebastida** [comment]
Oh - Fixing the help message to correctly represent the fact that the group is not optional.
