### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\u2714' in position 87: character maps to <undefined>

### ISSUE THREAD

**Issue by jdcarroll** [jorgebastida/awslogs#348]
"""

/aws/codebuild/asguard-dev a9f15662-75a0-487c-aba8-79d1418db112 ==> amazon-ebs: warning: /tmp/install.sh.2947/chef-16.7.61-1.el7.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 83ef826a: NOKEY
/aws/codebuild/asguard-dev a9f15662-75a0-487c-aba8-79d1418db112     amazon-ebs: Preparing...                          ########################################
/aws/codebuild/asguard-dev a9f15662-75a0-487c-aba8-79d1418db112     amazon-ebs: Updating / installing...
/aws/codebuild/asguard-dev a9f15662-75a0-487c-aba8-79d1418db112     amazon-ebs: chef-16.7.61-1.el7                    ########################################
/aws/codebuild/asguard-dev a9f15662-75a0-487c-aba8-79d1418db112     amazon-ebs: Thank you for installing Chef Infra Client! For help getting started visit https://learn.chef.io
/aws/codebuild/asguard-dev a9f15662-75a0-487c-aba8-79d1418db112     amazon-ebs: Creating directory: /tmp/packer-chef-client
/aws/codebuild/asguard-dev a9f15662-75a0-487c-aba8-79d1418db112     amazon-ebs: Uploading /tmp/validation.pem...
/aws/codebuild/asguard-dev a9f15662-75a0-487c-aba8-79d1418db112     amazon-ebs: Creating configuration file 'client.rb'
/aws/codebuild/asguard-dev a9f15662-75a0-487c-aba8-79d1418db112     amazon-ebs: Creating JSON attribute file
/aws/codebuild/asguard-dev a9f15662-75a0-487c-aba8-79d1418db112     amazon-ebs: Executing Chef: sudo chef-client --no-color -c /tmp/packer-chef-client/client.rb -j /tmp/packer-chef-client/first-boot.json
/aws/codebuild/asguard-dev a9f15662-75a0-487c-aba8-79d1418db112     amazon-ebs: [2021-04-29T19:10:28+00:00] INFO: Persisting a license for Chef Infra Client at path /etc/chef/accepted_licenses/chef_infra_client
/aws/codebuild/asguard-dev a9f15662-75a0-487c-aba8-79d1418db112     amazon-ebs: [2021-04-29T19:10:28+00:00] INFO: Persisting a license for Chef InSpec at path /etc/chef/accepted_licenses/inspec
/aws/codebuild/asguard-dev a9f15662-75a0-487c-aba8-79d1418db112     amazon-ebs: +---------------------------------------------+

 

You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new

 

Version:       0.14.0
Python:        3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]
boto3 version: 1.17.60
Platform:      Windows-10-10.0.19041-SP0
Args:          ['C:\\Users\\jmamscl\\src\\asgard\\cli\\.venv\\Scripts\\awslogs', 'get', '/aws/codebuild/asguard-dev', 'a9f15662-75a0-487c-aba8-79d1418db112', '-s1d', '--watch', '--profile', 'ami-warehouse-admin']
Config: {'aws_access_key_id': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'aws_session_token': 'SENSITIVE', 'aws_profile': 'SENSITIVE', 'aws_region': None, 'aws_endpoint_url': None, 'log_group_name': '/aws/codebuild/asguard-dev', 'log_stream_name': 'a9f15662-75a0-487c-aba8-79d1418db112', 'filter_pattern': None, 'watch': True, 'watch_interval': 1, 'output_group_enabled': True, 'output_stream_enabled': True, 'output_timestamp_enabled': False, 'output_ingestion_time_enabled': False, 'start': '1d', 'end': None, 'color': 'auto', 'query': None, 'func': 'list_logs'}

 

Traceback (most recent call last):
  File "c:\users\jmamscl\src\asgard\cli\.venv\lib\site-packages\awslogs\bin.py", line 179, in main
    getattr(logs, options.func)()
  File "c:\users\jmamscl\src\asgard\cli\.venv\lib\site-packages\awslogs\core.py", line 229, in list_logs
    consumer()
  File "c:\users\jmamscl\src\asgard\cli\.venv\lib\site-packages\awslogs\core.py", line 218, in consumer
    print(' '.join(output))
  File "C:\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2714' in position 87: character maps to <undefined>
 
"""

**Comment by jorgebastida** [comment]
Fixed as part of https://github.com/jorgebastida/awslogs/pull/396
