### ISSUE TITLE
Remove group name and name file logs

### ISSUE THREAD

**Issue by mserranoobsidiam** [jorgebastida/awslogs#353]
I can't hide the group name and file name from the command output, is there a way to do it?

![image](https://user-images.githubusercontent.com/82068509/124040768-c8c26d00-d9c2-11eb-9ae9-73739776ffa3.png)

this

/aws/ecs/obsicash-service java/obsicash-service-dev-task/d0ca42a6a4d54f9998b6f14bec7a0ec3

**Comment by AntonUspehov** [comment]
@mserranoobsidiam do you mean this?
```sh
  -G, --no-group        Do not display group name
  -S, --no-stream       Do not display stream name
```

If so you shoud use something like:
`awslogs get -S -G <log_group_name> <log_stream_name>`

**Comment by mserranoobsidiam** [comment]
yes it is!!! thank you so mucho
