### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\u0413' in position 286: character maps to <undefined>

### ISSUE THREAD

**Issue by iHeluani** [jorgebastida/awslogs#366]
Version:       0.14.0
Python:        3.8.4 (tags/v3.8.4:dfa645a, Jul 13 2020, 16:46:45) [MSC v.1924 64 bit (AMD64)]
boto3 version: 1.20.15
Platform:      Windows-10-10.0.18362-SP0
Args:          ['C:\\Python38\\Scripts\\awslogs', 'get', 'prod-HagueFiles', '-s', '3d']
Config: {'aws_access_key_id': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'aws_session_token': 'SENSITIVE', 'aws_profile': 'SENSITIVE', 'aws_region': None, 'aws_endpoint_url': None, 'log_group_name': 'prod-HagueFiles', 'log_stream_name': 'ALL', 'filter_pattern': None, 'watch': False, 'watch_interval': 1, 'output_group_enabled': True, 'output_stream_enabled': True, 'output_timestamp_enabled': False, 'output_ingestion_time_enabled': False, 'start': '3d', 'end': None, 'color': 'auto', 'query': None, 'func': 'list_logs'}

Traceback (most recent call last):
  File "c:\python38\lib\site-packages\awslogs\bin.py", line 179, in main
    getattr(logs, options.func)()
  File "c:\python38\lib\site-packages\awslogs\core.py", line 229, in list_logs
    consumer()
  File "c:\python38\lib\site-packages\awslogs\core.py", line 218, in consumer
    print(' '.join(output))
  File "c:\python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0413' in position 286: character maps to <undefined>

**Comment by jorgebastida** [comment]
Fixed as part of https://github.com/jorgebastida/awslogs/pull/396
