### ISSUE TITLE
Encoding issue?

### ISSUE THREAD

**Issue by sudheeshkmk** [jorgebastida/awslogs#376]
You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new

Version:       0.14.0
Python:        3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
boto3 version: 1.24.51
Platform:      Windows-10-10.0.19042-SP0
Args:          ['C:\\Users\\EI7572\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\awslogs', 'get', '/aws/datasync/pol-sync', 'ALL', "--start='15-08-2022", "07:00'"]
Config: {'aws_access_key_id': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'aws_session_token': 'SENSITIVE', 'aws_profile': 'SENSITIVE', 'aws_region': None, 'aws_endpoint_url': None, 'log_group_name': '/aws/datasync/pol-sync', 'log_stream_name': 'ALL', 'filter_pattern': None, 'watch': False, 'watch_interval': 1, 'output_group_enabled': True, 'output_stream_enabled': True, 'output_timestamp_enabled': False, 'output_ingestion_time_enabled': False, 'start': "'15-08-2022", 'end': None, 'color': 'auto', 'query': None, 'func': 'list_logs'}

Traceback (most recent call last):
  File "C:\Users\EI7572\AppData\Local\Programs\Python\Python310\lib\site-packages\awslogs\bin.py", line 179, in main
    getattr(logs, options.func)()
  File "C:\Users\EI7572\AppData\Local\Programs\Python\Python310\lib\site-packages\awslogs\core.py", line 229, in list_logs
    consumer()
  File "C:\Users\EI7572\AppData\Local\Programs\Python\Python310\lib\site-packages\awslogs\core.py", line 218, in consumer
    print(' '.join(output))
  File "C:\Users\EI7572\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 173-174: character maps to <undefined>

C:\Users\EI7572>awslogs get /aws/datasync/pol-sync ALL --start='15-08-2022 07:00' >> errlogdsync.txt

You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new

Version:       0.14.0
Python:        3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
boto3 version: 1.24.51
Platform:      Windows-10-10.0.19042-SP0
Args:          ['C:\\Users\\EI7572\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\awslogs', 'get', '/aws/datasync/pol-sync', 'ALL', "--start='15-08-2022", "07:00'"]
Config: {'aws_access_key_id': 'SENSITIVE', 'aws_secret_access_key': 'SENSITIVE', 'aws_session_token': 'SENSITIVE', 'aws_profile': 'SENSITIVE', 'aws_region': None, 'aws_endpoint_url': None, 'log_group_name': '/aws/datasync/pol-sync', 'log_stream_name': 'ALL', 'filter_pattern': None, 'watch': False, 'watch_interval': 1, 'output_group_enabled': True, 'output_stream_enabled': True, 'output_timestamp_enabled': False, 'output_ingestion_time_enabled': False, 'start': "'15-08-2022", 'end': None, 'color': 'auto', 'query': None, 'func': 'list_logs'}

Traceback (most recent call last):
  File "C:\Users\EI7572\AppData\Local\Programs\Python\Python310\lib\site-packages\awslogs\bin.py", line 179, in main
    getattr(logs, options.func)()
  File "C:\Users\EI7572\AppData\Local\Programs\Python\Python310\lib\site-packages\awslogs\core.py", line 229, in list_logs
    consumer()
  File "C:\Users\EI7572\AppData\Local\Programs\Python\Python310\lib\site-packages\awslogs\core.py", line 218, in consumer
    print(' '.join(output))
  File "C:\Users\EI7572\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 173-174: character maps to <undefined>

**Comment by MartinStarkNL** [comment]
I got the same issue on Mac OSX. Any recommendation how to proceed from here?

**Comment by jorgebastida** [comment]
Fixed as part of https://github.com/jorgebastida/awslogs/pull/396
