### ISSUE TITLE
rewrite setup.py to `pbr` and `setup.cfg`

### ISSUE THREAD

**Issue by vlcinsky** [jorgebastida/awslogs#38]
This is a proposal, not a bug.

Existing `setup.py` is already using `pbr`, probably to incorporate `test` command.

If we rewrite the `setup.py` into `pbr`, it would result in:
- all existing functionality still present
- 3-lines long `setup.py`
- all metadata moved into `setup.cfg`
- version being derived from git tag (we may decide for other method, like having version hard coded in this file or in external one)
- autogenerated ChangeLog based on commit messages (if we want that)
- autogenerated AUTHORS from commit messages.
- requirements.txt being externalized from `setup.py`

Apart from cleaning the code, we could resolve the issue #37 by that.

**Comment by jorgebastida** [comment]
See my comment https://github.com/jorgebastida/awslogs/pull/50#issuecomment-202032114 Thanks!
