### ISSUE TITLE
How do I use hyphenated characters in filter pattern properties?

### ISSUE THREAD

**Issue by alsdud154** [jorgebastida/awslogs#381]
I want to filter the thread name.
Thread names contain characters that contain hyphens.
How do I use hyphenated characters in filter pattern properties?
I want to filter only ORDER-ITEM-1 in the red area as shown in the image.

This is the code I tried.
`awslogs get /ecs/cafe24-webhook ALL --s='3h' --profile cafe24 --filter-pattern "ORDER ITEM 1"`

This is the code I want. But the filter doesn't work.
`awslogs get /ecs/cafe24-webhook ALL --s='3h' --profile cafe24 --filter-pattern "ORDER-ITEM-1"`

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/61396939/207263557-d7f29da1-f068-4e73-9f99-f4c35259e496.png">

**Comment by leonroy** [comment]
having this issue too...

**Comment by alsdud154** [comment]
I was able to solve it by writing single quotes -> double quotes in filter-pattern.

`awslogs get /ecs/cafe24-webhook ALL --s='3h' --profile cafe24 --filter-pattern='"ORDER-ITEM-1"'`

**Comment by alsdud154** [comment]
> having this issue too...

I left a workaround.
