### ISSUE TITLE
rewrite to use `tox`

### ISSUE THREAD

**Issue by vlcinsky** [jorgebastida/awslogs#39]
Currently, tests are run by `$ python setup.py test`.

To run this test in multiple python versions requires manually switching the python version for each test or wait, until Travis does the work.

Rewriting test to `tox` would allow starting test in all locally available python versions by simple `$ tox` call.

The rewrite should keep all existing functionality, namely:
- run all existing test cases
- run test coverage evaluation

**Comment by jorgebastida** [comment]
Done https://github.com/jorgebastida/awslogs/pull/69
