### ISSUE TITLE
Crash when attempting get:

### ISSUE THREAD

**Issue by grantatsyncbak** [jorgebastida/awslogs#4]
The command:

awslogs --aws-region us-east-1 get qaCatcher  --start='10m ago' | grep ERROR

The output:

You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/awslogs/issues/new
--------------------------------------------------------------------------------
Version: 0.0.1
Python: 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2]
boto version: 2.38.0
Platform: Linux-3.13.0-49-generic-x86_64-with-Ubuntu-14.04-trusty
Config: {'output_group_enabled': True, 'end': None, 'aws_secret_access_key': 'SENSITIVE', 'log_stream_name': u'ALL', 'watch': False, 'aws_region': u'us-east-1', 'start': u'1h ago', 'log_group_name': u'qaCatcher', 'func': 'list_logs', 'aws_access_key_id': 'SENSITIVE', 'color_enabled': True, 'output_stream_enabled': True}
Args: ['/usr/local/bin/awslogs', '--aws-region', 'us-east-1', 'get', 'qaCatcher', '--start=1h ago']

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/awslogs/bin.py", line 116, in main
    getattr(logs, options.func)()
  File "/usr/local/lib/python2.7/dist-packages/awslogs/core.py", line 224, in list_logs
    pool.join()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pool.py", line 100, in join
    self._empty_event.wait(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/gevent/event.py", line 77, in wait
    result = self.hub.switch()
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 331, in switch
    return greenlet.switch(self)
LoopExit: This operation would block forever

**Comment by jorgebastida** [comment]
I've just pushed a new version (0.1.0) to pypi which should fix this issue.
https://pypi.python.org/pypi/awslogs/0.1.0
