### ISSUE TITLE
rewrite tests to `pytest`

### ISSUE THREAD

**Issue by vlcinsky** [jorgebastida/awslogs#40]
This is proposal, not a bug.

Currently, the only way to run the test I am aware of is by `$ python setup.py test`.

I do not know, if one can run the test selecting only specific test (what would speed up development of particular features).

Rewrite to `pytest` would result in:
- moving all existing tests into `tests` folder (preserve all existing test cases)
- more modular test suite code
- nicer problem report in case of failure (nicely coloured, more expressive)
- easy option to discover existing tests without running them
- easy option to run just particular test
- allow coverage report

I am asking for an opinion before I dive into it as it takes few hours of work.

**Comment by jorgebastida** [comment]
After https://github.com/jorgebastida/awslogs/pull/69 we are ow using pytests :D Thanks!
