### ISSUE TITLE
misspelled options in `bin.py`

### ISSUE THREAD

**Issue by vlcinsky** [jorgebastida/awslogs#41]
Line 135 in `bin.py` https://github.com/jorgebastida/awslogs/blob/master/awslogs/bin.py#L135 is misspelled:

    if options.aws_profile:
        os.environ['AWS_PROFILE'] = option.aws_profile

As there is no variable `option`, it would fail. It shall read:

    if options.aws_profile:
        os.environ['AWS_PROFILE'] = options.aws_profile

**Comment by jorgebastida** [comment]
Already fixed in master

**Comment by vlcinsky** [comment]
Great.
Just a note: the line was not covered by tests and it serves to me as clear example, why is good coverage relevant.

See https://coveralls.io/builds/4733189/source?filename=awslogs/bin.py#L135
