### ISSUE TITLE
refactor the code to follow PEP008

### ISSUE THREAD

**Issue by vlcinsky** [jorgebastida/awslogs#42]
On some place are lines exceeding 80 characters what is not following PEP008.

On other places there are variables or imports declared but not used.

Refactoring shall not be difficult and shall make the code easier to maintain in future.

Anyway, I did not dare to do so at the moment there were pending pull request, as it would require authors to update their contributions.

**Comment by jorgebastida** [comment]
Done an initial cleanup in https://github.com/jorgebastida/awslogs/pull/54
Will review your tox PR https://github.com/jorgebastida/awslogs/pull/50 as soon as I have some spare time - in the meantime flake8 will do the job... ish.

**Comment by vlcinsky** [comment]
I like the way you test and automate quality checks.

Question: Is it really necessary to allow max 120 characters per line?

- PEP008 recommends 79 chars
- [Google Python Style Guide recommend 80](https://google.github.io/styleguide/pyguide.html#Line_length)
- [SaltStack style](https://docs.saltstack.com/en/latest/topics/development/conventions/style.html#line-length) prefers to follow PEP008 but allows exceptions as you use (120) chars.
- PyCharm defaults to 120 chars limit

There is also [related SO question on this topic](http://stackoverflow.com/questions/88942/why-does-python-pep-8-specify-a-maximum-line-length-of-79-characters).

As can be seen from my links, 79 or 80 chars per line is often used, but there are others setting the limit to 120.

It is definitely your choice, I just would like to learn from you the reasons as I see, your coding style and habits are mature in many aspects.
