### ISSUE TITLE
Introduce pattern searching on the AWS side (like filter-log-events does).

### ISSUE THREAD

**Issue by pwilczynskiclearcode** [jorgebastida/awslogs#43]
http://docs.aws.amazon.com/cli/latest/reference/logs/filter-log-events.html gives the possibility to filter events on the AWS side instead of downloading all logs and grep'ing them locally.

awslogs has really nice syntax while `aws logs filter-log-events` has nice feature with awful syntax.

**Comment by vlcinsky** [comment]
What version of `awslogs` are you using?

See issue #25, which is asking for exactly that and what is already implemented in `awslogs` version `0.2.0`.

**Comment by pwilczynskiclearcode** [comment]
oversight

**Comment by vlcinsky** [comment]
@pwilczynskiclearcode off topic: My grandfather used to use surname Wilczyński (changed to Vlčinský later on).

**Comment by pwilczynskiclearcode** [comment]
@vlcinsky Hi then :)
