### ISSUE TITLE
Why we have `pbr` in `tests_require` in `setup.py`

### ISSUE THREAD

**Issue by vlcinsky** [jorgebastida/awslogs#49]
@jorgebastida
 
on line 19 of `setup.py` https://github.com/jorgebastida/awslogs/blob/master/setup.py#L19 there is:

    if sys.version_info < (3, 3):
        tests_require.append('pbr>=0.11,<1.7.0')
        tests_require.append('mock>=1.0.0')

I wonder
- why we have it there. I did not find any use of it even in tests
- do we have any experience with `pbr` version 1.8.0 not being usable?

Originally I thought, this piece of code will become obsolete by rewriting the `setup.py` to use `pbr`, see issue #38, but working on it, I hit strange problems. One of findings is, that `pbr` has version `1.8.0` but even `pypi` reports the latest version being `0.11.0`. On launchpad I have found some notes about problems with version `1.8.0` due to conflicts with Sphinx and planned to be blacklisted. See https://bugs.launchpad.net/pbr/+bug/1496882

Currently I have setup.py rewritten to use `pbr`, and `tox` testing in place, but when run, it rejects installing `awslogs` dependencies. Any insight into this `pbr` related problem is welcome.

**Comment by vlcinsky** [comment]
After long fight with exotic problems I have in my PR #50 this problem resolved - it runs and passes all tests.

**Comment by vlcinsky** [comment]
After few days of work on PR #50 I am rather unhappy with bunch of unexpected problems (which originate out of awslogs package).

Thas if why following lines are not really focused on pure facts. I am writing them here hoping, someone might give me a hint, which direction to go with better chance to succeed.

## Problems experienced

- installing `mock` package (required for python 2.x) sometime does not install required `pbr` package.
- very strange "half-way installed" status for `pbr`:
  - I was unable to uninstall or install pbr into virtualenv with messages like `Not uninstalling pbr at /home/javl/sandbox/awslogs/github/awslogs/pbr-1.8.1-py2.7.egg, outside environment /home/javl/sandbox/awslogs/github/awslogs/.tox/py27`.
  - trying to install `pbr` by `$ pip install pbr` reported `Requirement already satisfied (use --upgrade to upgrade): pbr in ./pbr-1.8.1-py2.7.egg`
  - following attempt to import `pbr` failed with `ImportError: No module named pbr.`
- https://github.com/testing-cabal/mock/issues/311 is describing the problem I have, `mock` being dependent on `pbr` is causing problems.
- installation of packages and related tests are very sensitive to versions of `pbr` and `mock`. Currently I am not able to find out the pattern to follow to deliver reliable solution - in one commit things are working, in another the tests start failing on problems to import `mock` in Python 2.7 due to missing `pbr`.

## Which way to go? (use or not `pbr`, `mock`...)

When I found the `pbr` package, I was happy to see it and use it in couple of my packages. Not only it strongly simplifies `setup.py`, but it is really used in huge project `openstack` so I was expecting good usability.

With `awslogs` it is the first time combined with `mock`. And I am not sure, where are the origins of the problems. Possible roots of problems might be:
- `mock` having runtime dependency on `pbr`
- `pbr` doing too much magic messing up installed packages
- combination of built time and runtime `pbr` use is causing strange effects

And the options I see as possible direction to go:
- forget about using `pbr` for building `awslogs`, be happy it installs for use with `mock` in Python 2.x
- find alternative to `mock`, which does not mess up with `pbr` at runtim
- wait until someone fixes `pbr` or `mock`

Any ideas welcome.

**Comment by vlcinsky** [comment]
Problems resolved.

When experimenting with pytest-cov plugin I set up PYTHONPATH to ".".
`pbr` have created egg in the same directory. And for this reason, for pip or setuptools `pbr` seemed to be installed and for python it was not importable.

All works well without PYTHONPATH tricky magic. I am really happy, those two days of `pbr` and `tox` related work become stable and PR #50 is passing all tests (incl. coverage).

Now I require `pbr>=1.8.1` as it supports environmental markers in requirements.txt files what simplifies few things.

@jorgebastida If you have any comments about required `pbr` version, let me know, otherwise feel free to close this issue.

**Comment by jorgebastida** [comment]
pbr is not longer part of the ``setup.py`` Thanks!
