### ISSUE TITLE
Bug: in case of streams that had no logs in a given time range all streams are returned.

### ISSUE THREAD

**Issue by pwilczynskiclearcode** [jorgebastida/awslogs#52]
I've got streams called `a-1`, `a-2` and using:

```
awslogs get -s 1m application/run.log a-1
```
returns all `application/run.log` logs.

And if I change it to
```
awslogs get -s 10m application/run.log a-1
```
Only logs from `a-1` are returned.

It seems that awslogs or boto/AWS returns all logs if stream regexp doesn't mach any entries.

**Comment by chadxz** [comment]
I ran into this the other day. was very confused by the behavior. Good to know I'm not crazy.

**Comment by nathanleiby** [comment]
+1 this is a confusing behavior

**Comment by nathanleiby** [comment]
Opened a PR for this issue: https://github.com/jorgebastida/awslogs/pull/60
