### ISSUE TITLE
Get just the logs

### ISSUE THREAD

**Issue by NerdPad** [jorgebastida/awslogs#75]
I send logs to CloudWatch in JSON format. When I use awslogs to fetch logs, I get the logs in the following format in console.

```<group> <stream name> <{JSON}>```

Is there a way I can just get JSON output in the console?

**Comment by digitalfiz** [comment]
Yes:

```
awslogs get <group> all | cut -d " " -f 3-
# or 
awslogs get <group> <stream> | cut -d " " -f 3-
```

**Comment by jorgebastida** [comment]
I think:
```bash
$ awslogs get -G -S <group> <stream>
```
would do the trick too
