### ISSUE TITLE
[Feature suggestion] Total Download Size

### ISSUE THREAD

**Issue by dhulihan** [jorgebastida/awslogs#81]
It would be useful if awslogs counted total bytes downloaded. Would be helpful for billing concerns 💰  .

**Comment by jorgebastida** [comment]
Monitoring the usage of aws resources looks like a complex and broad topic... way to big to get covered by every single of the individual tools which does use the aws api.

aws itself provides with cloudwatch metrics (per service) which would give you the chance to control your usage, and I am sure there are lots of services out there doing the same analyzing cloudtrail logs etc...

Thank you very much for the suggestion.
