### ISSUE TITLE
time range from date to offset, eg --start="2016-08-16T07:39:59" -A="2h" -B="1h"

### ISSUE THREAD

**Issue by graingert** [jorgebastida/awslogs#86]
I'd like to be able to set a specific time, then get 2h, 1d etc after or around it

eg `--start="2016-08-16T07:39:59" -A="2h" -B="2h"` (--after --before)

or `--start="2016-08-16T07:39:59" -C="2h"` (--context)

**Comment by jorgebastida** [comment]
I understand why this might be helpful... but I think I prefer to keep the simple ``--start`` ``--end`` api and not introduce more "magic". Thanks for the idea!
