### ISSUE TITLE
Allow GROUP globbing or expression

### ISSUE THREAD

**Issue by zanona** [jorgebastida/awslogs#90]
Hey @jorgebastida,
Thanks a lot for this library. I am just starting logging with cloudwatch and I am not sure I am missing something but for example, sometimes one of my groups is directly related to another group (i.e: A lambda function calling another one).

So in this case it would be great if I could be able to aggregate log results from more than one group let's say

`awslogs get /aws/lambda/{auth,redis} --start='2h ago'`

I would be quite nice to see those logs in chronologically sorted as well.

Is this by any change a good idea or would you recommend something else?

Thanks in advance.

**Comment by natesilva** [comment]
Even a `*` wildcard `myapp/*` would be great.

**Comment by jorgebastida** [comment]
That would be a great addition... but unfortunately, AWS doesn't provide any api to do so :/ See https://boto3.readthedocs.io/en/latest/reference/services/logs.html#CloudWatchLogs.Client.filter_log_events 

If in the future they make this possible, I would add that functionality.... sorry!

**Comment by aidansteele** [comment]
@jorgebastida Would you be open to a PR that does the aggregation on the client-side? i.e. poll each of the logs and multiplex the output in this app.
